coverage:
  status:
    patch: false
    project:
      default:
        # basic
        target: auto # default
        threshold: 5.0
        base: auto
        # flags:
        #   - unit
        paths:
          - src
        # advanced settings
        # branches:
        #   - main
        # if_ci_failed: error # success, failure, error, ignore
